
# =============================================================================
#  TMUX CONFIGURATION
# =============================================================================
#  Author: Aravinth
#  Prefix: C-Space (Ctrl+Space)
# =============================================================================


# =============================================================================
#  1. GENERAL OPTIONS
# =============================================================================

# Prefix key (C-a instead of C-b)
unbind C-b              # Unbind the default prefix key
set -g prefix C-Space   # Set new prefix key to Ctrl+Space

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "🔄 tmux config reloaded"


# =============================================================================
#  2. WINDOW OPTIONS
# =============================================================================

# Window behavior
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed
# set -g @powerkit_active_window_show_index "false"
# set -g @powerkit_inactive_window_show_index "false"


# =============================================================================
#  2. Display Popup
# =============================================================================

bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"


# =============================================================================
#  4. PLUGINS (TPM)
# =============================================================================

# TPM - Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# Status bar
set -g @plugin 'fabioluciano/tmux-powerkit'

# Better tmux keymaps
set -g @plugin 'tmux-plugins/tmux-sensible'

# Session manager
set -g @plugin 'omerxx/tmux-sessionx'

# =============================================================================
#  5. POWERKIT CONFIGURATION
# =============================================================================

# -----------------------------------------------------------------------------
#  Theme
# -----------------------------------------------------------------------------
set -g @powerkit_transparent "true"
set -g @powerkit_theme "kanagawa"
set -g @powerkit_theme_variant "light"


# -----------------------------------------------------------------------------
#  Layout & Appearance
# -----------------------------------------------------------------------------
set -g @powerkit_status_order "session,windows,plugins"
set -g @powerkit_elements_spacing "false"
# set -g @powerkit_window_index_icons "true"
set -g @powerkit_edge_separator_style "rounded:all"
set -g @powerkit_status_position "bottom"


# -----------------------------------------------------------------------------
#  Plugins Selection
# -----------------------------------------------------------------------------
# PowerKit configuration
set -g @powerkit_plugins "memory,battery"
set -g @powerkit_plugin_memory_format "percent"



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
